In [9]:
import pandas as pd
df = pd.DataFrame({
    'A': [10, 20, 30],
    'B': [100, 200, 300]
}, index=['x', 'y', 'z'])

In [18]:
df

    A    B
x  10  100
y  20  200
z  30  300

In [26]:
df['A']

x    10
y    20
z    30
Name: A, dtype: int64

In [28]:
df['C'] = [2,65,98]
df

    A    B   C
x  10  100   2
y  20  200  65
z  30  300  98

In [38]:
df.loc['g'] = [23,78,98]
df

    A    B   C
x  23   78  98
y  20  200  65
z  30  300  98
0  23   78  98
g  23   78  98

In [54]:
df.loc[1] = [23,78,98]

In [56]:
df

    A    B   C
x  23   78  98
y  23   78  98
z  30  300  98
0  23   78  98
g  23   78  98
1  23   78  98

# Assignmet 1

In [3]:
import pandas as pd

1. Find count of each flower type

In [5]:
iris = pd.read_csv(r"C:\Users\Hp\Downloads\iris.csv")
iris.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [7]:
df = iris.copy()
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [23]:
df.variety.unique()

array(['Setosa', 'Versicolor', 'Virginica'], dtype=object)

In [65]:
count1 = df['variety'].value_counts()['Setosa']
count1

50

In [71]:
count2 = df['variety'].value_counts()['Versicolor']
count2

50

In [73]:
count3 = df['variety'].value_counts()['Virginica']
count3

50

In [75]:
print(count1, count2, count3, sep = "  ")

50  50  50

2. Find the data of flower Virginica where petal length > 1.5

In [83]:
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [113]:
mask = (df['petal.length'] > 1.5) & (df['variety'] == 'Virginica')
df[mask]

     sepal.length  sepal.width  petal.length  petal.width    variety
100           6.3          3.3           6.0          2.5  Virginica
101           5.8          2.7           5.1          1.9  Virginica
102           7.1          3.0           5.9          2.1  Virginica
103           6.3          2.9           5.6          1.8  Virginica
104           6.5          3.0           5.8          2.2  Virginica
105           7.6          3.0           6.6          2.1  Virginica
106           4.9          2.5           4.5          1.7  Virginica
107           7.3          2.9           6.3          1.8  Virginica
108           6.7          2.5           5.8          1.8  Virginica
109           7.2          3.6           6.1          2.5  Virginica
110           6.5          3.2           5.1          2.0  Virginica
111           6.4          2.7           5.3          1.9  Virginica
112           6.8          3.0           5.5          2.1  Virginica
113           5.7          2.5           5.0          2.0  Virginica
114           5.8          2.8           5.1          2.4  Virginica
115           6.4          3.2           5.3          2.3  Virginica
116           6.5          3.0           5.5          1.8  Virginica
117           7.7          3.8           6.7          2.2  Virginica
118           7.7          2.6           6.9          2.3  Virginica
119           6.0          2.2           5.0          1.5  Virginica
120           6.9          3.2           5.7          2.3  Virginica
121           5.6          2.8           4.9          2.0  Virginica
122           7.7          2.8           6.7          2.0  Virginica
123           6.3          2.7           4.9          1.8  Virginica
124           6.7          3.3           5.7          2.1  Virginica
125           7.2          3.2           6.0          1.8  Virginica
126           6.2          2.8           4.8          1.8  Virginica
127           6.1          3.0           4.9          1.8  Virginica
128           6.4          2.8           5.6          2.1  Virginica
129           7.2          3.0           5.8          1.6  Virginica
130           7.4          2.8           6.1          1.9  Virginica
131           7.9          3.8           6.4          2.0  Virginica
132           6.4          2.8           5.6          2.2  Virginica
133           6.3          2.8           5.1          1.5  Virginica
134           6.1          2.6           5.6          1.4  Virginica
135           7.7          3.0           6.1          2.3  Virginica
136           6.3          3.4           5.6          2.4  Virginica
137           6.4          3.1           5.5          1.8  Virginica
138           6.0          3.0           4.8          1.8  Virginica
139           6.9          3.1           5.4          2.1  Virginica
140           6.7          3.1           5.6          2.4  Virginica
141           6.9          3.1           5.1          2.3  Virginica
142           5.8          2.7           5.1          1.9  Virginica
143           6.8          3.2           5.9          2.3  Virginica
144           6.7          3.3           5.7          2.5  Virginica
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [111]:
df.loc[(df['variety'] == 'Virginica') & (df['petal.length'] > 1.5)]

     sepal.length  sepal.width  petal.length  petal.width    variety
100           6.3          3.3           6.0          2.5  Virginica
101           5.8          2.7           5.1          1.9  Virginica
102           7.1          3.0           5.9          2.1  Virginica
103           6.3          2.9           5.6          1.8  Virginica
104           6.5          3.0           5.8          2.2  Virginica
105           7.6          3.0           6.6          2.1  Virginica
106           4.9          2.5           4.5          1.7  Virginica
107           7.3          2.9           6.3          1.8  Virginica
108           6.7          2.5           5.8          1.8  Virginica
109           7.2          3.6           6.1          2.5  Virginica
110           6.5          3.2           5.1          2.0  Virginica
111           6.4          2.7           5.3          1.9  Virginica
112           6.8          3.0           5.5          2.1  Virginica
113           5.7          2.5           5.0          2.0  Virginica
114           5.8          2.8           5.1          2.4  Virginica
115           6.4          3.2           5.3          2.3  Virginica
116           6.5          3.0           5.5          1.8  Virginica
117           7.7          3.8           6.7          2.2  Virginica
118           7.7          2.6           6.9          2.3  Virginica
119           6.0          2.2           5.0          1.5  Virginica
120           6.9          3.2           5.7          2.3  Virginica
121           5.6          2.8           4.9          2.0  Virginica
122           7.7          2.8           6.7          2.0  Virginica
123           6.3          2.7           4.9          1.8  Virginica
124           6.7          3.3           5.7          2.1  Virginica
125           7.2          3.2           6.0          1.8  Virginica
126           6.2          2.8           4.8          1.8  Virginica
127           6.1          3.0           4.9          1.8  Virginica
128           6.4          2.8           5.6          2.1  Virginica
129           7.2          3.0           5.8          1.6  Virginica
130           7.4          2.8           6.1          1.9  Virginica
131           7.9          3.8           6.4          2.0  Virginica
132           6.4          2.8           5.6          2.2  Virginica
133           6.3          2.8           5.1          1.5  Virginica
134           6.1          2.6           5.6          1.4  Virginica
135           7.7          3.0           6.1          2.3  Virginica
136           6.3          3.4           5.6          2.4  Virginica
137           6.4          3.1           5.5          1.8  Virginica
138           6.0          3.0           4.8          1.8  Virginica
139           6.9          3.1           5.4          2.1  Virginica
140           6.7          3.1           5.6          2.4  Virginica
141           6.9          3.1           5.1          2.3  Virginica
142           5.8          2.7           5.1          1.9  Virginica
143           6.8          3.2           5.9          2.3  Virginica
144           6.7          3.3           5.7          2.5  Virginica
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

3. Find Min, max and avg for each kind of flower

In [231]:
mask = df['variety'] == 'Setosa'
df[mask].describe()

       sepal.length  sepal.width  petal.length  petal.width
count      50.00000    50.000000     50.000000    50.000000
mean        5.00600     3.428000      1.462000     0.246000
std         0.35249     0.379064      0.173664     0.105386
min         4.30000     2.300000      1.000000     0.100000
25%         4.80000     3.200000      1.400000     0.200000
50%         5.00000     3.400000      1.500000     0.200000
75%         5.20000     3.675000      1.575000     0.300000
max         5.80000     4.400000      1.900000     0.600000

In [233]:
min_setosa = df[mask].min().round(2)
min_setosa

sepal.length       4.3
sepal.width        2.3
petal.length       1.0
petal.width        0.1
variety         Setosa
dtype: object

In [235]:
max_setosa = df[mask].max()
max_setosa

sepal.length       5.8
sepal.width        4.4
petal.length       1.9
petal.width        0.6
variety         Setosa
dtype: object

In [237]:
mean_setosa = df[mask].mean(numeric_only = True).round(2)
mean_setosa

sepal.length    5.01
sepal.width     3.43
petal.length    1.46
petal.width     0.25
dtype: float64

In [239]:
df[mask].select_dtypes(include='number').agg(['min', 'max', 'mean']).round(2)

      sepal.length  sepal.width  petal.length  petal.width
min           4.30         2.30          1.00         0.10
max           5.80         4.40          1.90         0.60
mean          5.01         3.43          1.46         0.25

In [241]:
mask = df['variety'] == 'Versicolor'

In [243]:
df[mask].select_dtypes(include = 'number').agg(['min', 'max', 'mean']).round(2)

      sepal.length  sepal.width  petal.length  petal.width
min           4.90         2.00          3.00         1.00
max           7.00         3.40          5.10         1.80
mean          5.94         2.77          4.26         1.33

In [245]:
mask = df['variety'] == 'Virginica'

In [247]:
df[mask].select_dtypes(include = 'number').agg(['min', 'max', 'mean']).round(2)

      sepal.length  sepal.width  petal.length  petal.width
min           4.90         2.20          4.50         1.40
max           7.90         3.80          6.90         2.50
mean          6.59         2.97          5.55         2.03

In [249]:
df[mask].describe()

       sepal.length  sepal.width  petal.length  petal.width
count      50.00000    50.000000     50.000000     50.00000
mean        6.58800     2.974000      5.552000      2.02600
std         0.63588     0.322497      0.551895      0.27465
min         4.90000     2.200000      4.500000      1.40000
25%         6.22500     2.800000      5.100000      1.80000
50%         6.50000     3.000000      5.550000      2.00000
75%         6.90000     3.175000      5.875000      2.30000
max         7.90000     3.800000      6.900000      2.50000

# Assignment 2

In [ ]:
1. Find most dangerous city in J&K , num of attacks,  Group    --> Most attack in which city

In [35]:
terror = pd.read_csv(r"C:\Users\Hp\Downloads\terrorismData.csv")
terror.tail()

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
181686,2017.0,12.0,31.0,Somalia,Middle Shebelle,Sub-Saharan Africa,Ceelka Geelow,2.359673,45.385034,Armed Assault,1.0,2.0,Checkpoint,12/31/2017: Assailants opened fire on a Somali...,Al-Shabaab,Military,Firearms
181687,2017.0,12.0,31.0,Syria,Lattakia,Middle East & North Africa,Jableh,35.407278,35.942679,Bombing/Explosion,2.0,7.0,Hmeymim Air Base,12/31/2017: Assailants launched mortars at the...,Muslim extremists,Military,Explosives
181688,2017.0,12.0,31.0,Philippines,Maguindanao,Southeast Asia,Kubentog,6.900742,124.437908,Facility/Infrastructure Attack,0.0,0.0,Houses,12/31/2017: Assailants set fire to houses in K...,Bangsamoro Islamic Freedom Movement (BIFM),Private Citizens & Property,Incendiary
181689,2017.0,12.0,31.0,India,Manipur,South Asia,Imphal,24.798346,93.940430,Bombing/Explosion,0.0,0.0,Office,12/31/2017: Assailants threw a grenade at a Fo...,Unknown,Government (General),Explosives
181690,2017.0,12.0,31.0,Philippines,Maguindanao,Southeast Asia,Cotabato City,7.209594,124.241966,Bombing/Explosion,0.0,0.0,Unknown,12/31/2017: An explosive device was discovered...,Unknown,Unknown,Explosives

In [36]:
df = terror.copy()

In [378]:
mask = df['State'] == 'Jammu and Kashmir'

In [380]:
filtered_data = df[mask]
filtered_data

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
21744,1984.0,4.0,17.0,India,Jammu and Kashmir,South Asia,Bhela,33.315527,74.622476,Assassination,2.0,0.0,Gurbachan Singh Sandhar (Sikh lawyer) and wife,NaN,Sikh Extremists,Private Citizens & Property,Unknown
22108,1984.0,5.0,20.0,India,Jammu and Kashmir,South Asia,Jammu,32.726602,74.857026,Bombing/Explosion,1.0,0.0,bridge over a stream,NaN,Unknown,Transportation,Explosives
29677,1986.0,12.0,11.0,India,Jammu and Kashmir,South Asia,Madora,33.934929,75.154160,Bombing/Explosion,1.0,5.0,general post office complex,NaN,Unknown,Government (General),Unknown
33202,1988.0,1.0,21.0,India,Jammu and Kashmir,South Asia,Mand,32.888165,74.985168,Armed Assault,2.0,0.0,police unit,NaN,Unknown,Police,Firearms
33372,1988.0,2.0,7.0,India,Jammu and Kashmir,South Asia,Kherawali,32.523889,74.974444,Armed Assault,4.0,5.0,marriage reception,NaN,Sikh Extremists,Private Citizens & Property,Firearms
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181222,2017.0,12.0,11.0,India,Jammu and Kashmir,South Asia,Kralcheck Keller,33.732981,74.855559,Armed Assault,2.0,1.0,Van,12/11/2017: Assailants opened fire on a Jammu ...,Jaish-e-Mohammad (JeM),Business,Firearms
181396,2017.0,12.0,18.0,India,Jammu and Kashmir,South Asia,Baramulla district,34.191218,74.350010,Bombing/Explosion,0.0,0.0,Police Station,12/18/2017: Assailants threw a grenade at a po...,Unknown,Police,Explosives
181414,2017.0,12.0,19.0,India,Jammu and Kashmir,South Asia,Pulwama district,33.873538,74.899019,Bombing/Explosion,0.0,0.0,Police Line,12/19/2017: Assailants fired a rifle grenade a...,Unknown,Police,Explosives
181476,2017.0,12.0,22.0,India,Jammu and Kashmir,South Asia,Srinagar,34.083740,74.789902,Armed Assault,0.0,0.0,Post,12/22/2017: Assailants threw two petrol bombs ...,Unknown,Police,Incendiary
181672,2017.0,12.0,31.0,India,Jammu and Kashmir,South Asia,Lethapora,33.966527,74.964225,Armed Assault,8.0,3.0,Camp,12/31/2017: Assailants armed with grenades and...,Jaish-e-Mohammad (JeM),Police,Explosives

In [422]:
grp_mask = filtered_data['Group'] != 'Unknown'

In [426]:
filtered_data = filtered_data[grp_mask]

In [428]:
filtered_data

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
21744,1984.0,4.0,17.0,India,Jammu and Kashmir,South Asia,Bhela,33.315527,74.622476,Assassination,2.0,0.0,Gurbachan Singh Sandhar (Sikh lawyer) and wife,NaN,Sikh Extremists,Private Citizens & Property,Unknown
33372,1988.0,2.0,7.0,India,Jammu and Kashmir,South Asia,Kherawali,32.523889,74.974444,Armed Assault,4.0,5.0,marriage reception,NaN,Sikh Extremists,Private Citizens & Property,Firearms
35266,1988.0,7.0,31.0,India,Jammu and Kashmir,South Asia,Srinagar,34.083740,74.789902,Bombing/Explosion,0.0,0.0,Srinagar Club,NaN,Sikh Extremists,Private Citizens & Property,Explosives
35267,1988.0,7.0,31.0,India,Jammu and Kashmir,South Asia,Srinagar,34.083740,74.789902,Bombing/Explosion,0.0,0.0,Telegraph Office,NaN,Sikh Extremists,Business,Explosives
35273,1988.0,7.0,31.0,India,Jammu and Kashmir,South Asia,Pundal,33.275000,74.474167,Assassination,3.0,0.0,Private Family,NaN,Sikh Extremists,Private Citizens & Property,Firearms
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180727,2017.0,11.0,24.0,India,Jammu and Kashmir,South Asia,Senzen,33.839956,75.001181,Hostage Taking (Kidnapping),1.0,0.0,Member of 175th Battalion: Muhammad Irfan Dar,11/24/2017: Assailants abducted Muhammad Irfan...,Hizbul Mujahideen (HM),Terrorists/Non-State Militia,Firearms
181028,2017.0,12.0,4.0,India,Jammu and Kashmir,South Asia,Bonigam,33.634505,75.135488,Armed Assault,3.0,1.0,Convoy,12/04/2017: Assailants opened fire on a milita...,Lashkar-e-Taiba (LeT),Military,Firearms
181029,2017.0,12.0,4.0,India,Jammu and Kashmir,South Asia,Noorpora,33.906370,75.039940,Facility/Infrastructure Attack,0.0,0.0,Bank Branch,12/04/2017: Assailants raided a bank in Noorpo...,Ansar Ghazwat-ul-Hind,Business,Firearms
181222,2017.0,12.0,11.0,India,Jammu and Kashmir,South Asia,Kralcheck Keller,33.732981,74.855559,Armed Assault,2.0,1.0,Van,12/11/2017: Assailants opened fire on a Jammu ...,Jaish-e-Mohammad (JeM),Business,Firearms
181672,2017.0,12.0,31.0,India,Jammu and Kashmir,South Asia,Lethapora,33.966527,74.964225,Armed Assault,8.0,3.0,Camp,12/31/2017: Assailants armed with grenades and...,Jaish-e-Mohammad (JeM),Police,Explosives

In [438]:
city_counts = filtered_data['City'].value_counts()
city_counts

City
Srinagar     351
Unknown       49
Sopore        39
Jammu         25
Anantnag      25
            ...
Konibal        1
Ashmuqam       1
Narimarg       1
Malikpora      1
Lethapora      1
Name: count, Length: 277, dtype: int64

In [440]:
most_attacked_city = city_counts.idxmax()
most_attacked_city

'Srinagar'

In [442]:
attacks_count = city_counts.max()
attacks_count

351

In [468]:
grp_mask = filtered_data.loc[df['City'] == most_attacked_city, 'Group']
grp_mask

35266                 Sikh Extremists
35267                 Sikh Extremists
36074                Muslim Militants
36078                Muslim Militants
36079                Muslim Militants
                     ...
172155    Quit Kashmir Movement (QKM)
173509         Hizbul Mujahideen (HM)
173539            Tehrik al-Mojahedin
175806         Jaish-e-Mohammad (JeM)
177665          Lashkar-e-Taiba (LeT)
Name: Group, Length: 351, dtype: object

In [476]:
active_grp = grp_mask.value_counts().idxmax()
active_grp

'Muslim Separatists'

In [480]:
print(most_attacked_city, attacks_count, active_grp , sep = ' ')

Srinagar 351 Muslim Separatists

2. Find country with , max num of attacks, in which year

In [486]:
df.head()

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
0,1970.0,7.0,2.0,Dominican Republic,NaN,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,Assassination,1.0,0.0,Julio Guzman,NaN,MANO-D,Private Citizens & Property,Unknown
1,1970.0,0.0,0.0,Mexico,Federal,North America,Mexico city,19.371887,-99.086624,Hostage Taking (Kidnapping),0.0,0.0,"Nadine Chaval, daughter",NaN,23rd of September Communist League,Government (Diplomatic),Unknown
2,1970.0,1.0,0.0,Philippines,Tarlac,Southeast Asia,Unknown,15.478598,120.599741,Assassination,1.0,0.0,Employee,NaN,Unknown,Journalists & Media,Unknown
3,1970.0,1.0,0.0,Greece,Attica,Western Europe,Athens,37.997490,23.762728,Bombing/Explosion,NaN,NaN,U.S. Embassy,NaN,Unknown,Government (Diplomatic),Explosives
4,1970.0,1.0,0.0,Japan,Fukouka,East Asia,Fukouka,33.580412,130.396361,Facility/Infrastructure Attack,NaN,NaN,U.S. Consulate,NaN,Unknown,Government (Diplomatic),Incendiary

In [492]:
country_mask = df['Country'].value_counts()
country_mask

Country
Iraq             24635
Pakistan         14363
Afghanistan      12730
India            11958
Colombia          8288
                 ...
International        1
North Korea          1
Vatican City         1
New Hebrides         1
St. Lucia            1
Name: count, Length: 203, dtype: int64

In [494]:
country_max_attacks = country_mask.idxmax()
country_max_attacks

'Iraq'

In [496]:
num_of_attacks = country_mask.max()
num_of_attacks

24635

In [500]:
year_of_attacks = df.loc[df['Country'] == country_max_attacks, 'Year']
year_of_attacks

4385      1976.0
4393      1976.0
4402      1976.0
8688      1979.0
9688      1979.0
           ...
181669    2017.0
181670    2017.0
181671    2017.0
181674    2017.0
181679    2017.0
Name: Year, Length: 24635, dtype: float64

In [508]:
year_of_max_attacks = year_of_attacks.value_counts().idxmax()
year_of_max_attacks

2014.0

In [516]:
print(country_max_attacks, num_of_attacks, year_of_max_attacks, sep = '  ')

Iraq  24635  2014.0

3. Most Deadliest attack --> count of people killed,  country,  grp

In [523]:
df.head()

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
0,1970.0,7.0,2.0,Dominican Republic,NaN,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,Assassination,1.0,0.0,Julio Guzman,NaN,MANO-D,Private Citizens & Property,Unknown
1,1970.0,0.0,0.0,Mexico,Federal,North America,Mexico city,19.371887,-99.086624,Hostage Taking (Kidnapping),0.0,0.0,"Nadine Chaval, daughter",NaN,23rd of September Communist League,Government (Diplomatic),Unknown
2,1970.0,1.0,0.0,Philippines,Tarlac,Southeast Asia,Unknown,15.478598,120.599741,Assassination,1.0,0.0,Employee,NaN,Unknown,Journalists & Media,Unknown
3,1970.0,1.0,0.0,Greece,Attica,Western Europe,Athens,37.997490,23.762728,Bombing/Explosion,NaN,NaN,U.S. Embassy,NaN,Unknown,Government (Diplomatic),Explosives
4,1970.0,1.0,0.0,Japan,Fukouka,East Asia,Fukouka,33.580412,130.396361,Facility/Infrastructure Attack,NaN,NaN,U.S. Consulate,NaN,Unknown,Government (Diplomatic),Incendiary

In [531]:
people_killed_in_deadliest_attack = df['Killed'].max()
people_killed_in_deadliest_attack

1570.0

In [535]:
country_of_attack = df.loc[df['Killed'] == people_killed_in_deadliest_attack, 'Country']
country_of_attack

133518    Iraq
Name: Country, dtype: object

In [537]:
grp_responsible = df.loc[df['Killed'] == people_killed_in_deadliest_attack, 'Group']
grp_responsible

133518    Islamic State of Iraq and the Levant (ISIL)
Name: Group, dtype: object

In [549]:
print(int(people_killed_in_deadliest_attack), country_of_attack.iloc[0], grp_responsible.iloc[0], sep = '  ')

1570  Iraq  Islamic State of Iraq and the Levant (ISIL)

4.  26 May 2014 India --> Num of attacks,  grp done max attacks,  Ignore unknown grp

In [667]:
df.head()

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
0,1970.0,7.0,2.0,Dominican Republic,NaN,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,Assassination,1.0,0.0,Julio Guzman,NaN,MANO-D,Private Citizens & Property,Unknown
1,1970.0,0.0,0.0,Mexico,Federal,North America,Mexico city,19.371887,-99.086624,Hostage Taking (Kidnapping),0.0,0.0,"Nadine Chaval, daughter",NaN,23rd of September Communist League,Government (Diplomatic),Unknown
2,1970.0,1.0,0.0,Philippines,Tarlac,Southeast Asia,Unknown,15.478598,120.599741,Assassination,1.0,0.0,Employee,NaN,Unknown,Journalists & Media,Unknown
3,1970.0,1.0,0.0,Greece,Attica,Western Europe,Athens,37.997490,23.762728,Bombing/Explosion,NaN,NaN,U.S. Embassy,NaN,Unknown,Government (Diplomatic),Explosives
4,1970.0,1.0,0.0,Japan,Fukouka,East Asia,Fukouka,33.580412,130.396361,Facility/Infrastructure Attack,NaN,NaN,U.S. Consulate,NaN,Unknown,Government (Diplomatic),Incendiary

In [669]:
filtered_data = df[df['Country'] == 'India']
filtered_data

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
3857,1976.0,5.0,26.0,India,Delhi,South Asia,New Delhi,28.585836,77.153336,Bombing/Explosion,0.0,0.0,New Delhi airport,NaN,Unknown,Airports & Aircraft,Explosives
5327,1977.0,9.0,28.0,India,Maharashtra,South Asia,Bombay,19.075984,72.877656,Hijacking,0.0,0.0,DC-8,NaN,Japanese Red Army (JRA),Airports & Aircraft,Firearms
7337,1979.0,1.0,13.0,India,Assam,South Asia,Unknown,26.200605,92.937574,Armed Assault,NaN,NaN,patrol,NaN,Naga People,Police,Firearms
7342,1979.0,1.0,14.0,India,Manipur,South Asia,Imphal,24.798346,93.940430,Assassination,3.0,0.0,"Sudhir Kumar Singh, R.K. Sanajoaba Singh, Indr...",NaN,Unknown,Government (General),Firearms
8174,1979.0,4.0,26.0,India,Manipur,South Asia,Unknown,24.663717,93.906269,Armed Assault,4.0,0.0,Indian security force in front of jeep,NaN,Meitei extremists,Police,Firearms
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181663,2017.0,12.0,30.0,India,Kerala,South Asia,Koothuparamba,11.831902,75.565432,Bombing/Explosion,0.0,0.0,Koothuparamba Police Station,12/30/2017: Assailants threw an explosive devi...,Unknown,Police,Explosives
181665,2017.0,12.0,30.0,India,Chhattisgarh,South Asia,Toylanka,18.802725,81.497666,Facility/Infrastructure Attack,0.0,0.0,Road Construction Site,12/30/2017: Assailants set fire to seven vehic...,Communist Party of India - Maoist (CPI-Maoist),Business,Firearms
181672,2017.0,12.0,31.0,India,Jammu and Kashmir,South Asia,Lethapora,33.966527,74.964225,Armed Assault,8.0,3.0,Camp,12/31/2017: Assailants armed with grenades and...,Jaish-e-Mohammad (JeM),Police,Explosives
181684,2017.0,12.0,31.0,India,Assam,South Asia,Hungrum,25.180162,93.015788,Hostage Taking (Kidnapping),0.0,0.0,Personal Security Officer of Council Member Ih...,12/31/2017: Assailants abducted Prafulla Phuka...,Zeliangrong United Front,Government (General),Firearms
181689,2017.0,12.0,31.0,India,Manipur,South Asia,Imphal,24.798346,93.940430,Bombing/Explosion,0.0,0.0,Office,12/31/2017: Assailants threw a grenade at a Fo...,Unknown,Government (General),Explosives

In [670]:
filtered_data['Date'] = pd.to_datetime(filtered_data[['Year', 'Month', 'Day']], errors='coerce')
filtered_data

C:\Users\Hp\AppData\Local\Temp\ipykernel_3796\1242893894.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data['Date'] = pd.to_datetime(filtered_data[['Year', 'Month', 'Day']], errors='coerce')

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type,Date
3857,1976.0,5.0,26.0,India,Delhi,South Asia,New Delhi,28.585836,77.153336,Bombing/Explosion,0.0,0.0,New Delhi airport,NaN,Unknown,Airports & Aircraft,Explosives,1976-05-26
5327,1977.0,9.0,28.0,India,Maharashtra,South Asia,Bombay,19.075984,72.877656,Hijacking,0.0,0.0,DC-8,NaN,Japanese Red Army (JRA),Airports & Aircraft,Firearms,1977-09-28
7337,1979.0,1.0,13.0,India,Assam,South Asia,Unknown,26.200605,92.937574,Armed Assault,NaN,NaN,patrol,NaN,Naga People,Police,Firearms,1979-01-13
7342,1979.0,1.0,14.0,India,Manipur,South Asia,Imphal,24.798346,93.940430,Assassination,3.0,0.0,"Sudhir Kumar Singh, R.K. Sanajoaba Singh, Indr...",NaN,Unknown,Government (General),Firearms,1979-01-14
8174,1979.0,4.0,26.0,India,Manipur,South Asia,Unknown,24.663717,93.906269,Armed Assault,4.0,0.0,Indian security force in front of jeep,NaN,Meitei extremists,Police,Firearms,1979-04-26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181663,2017.0,12.0,30.0,India,Kerala,South Asia,Koothuparamba,11.831902,75.565432,Bombing/Explosion,0.0,0.0,Koothuparamba Police Station,12/30/2017: Assailants threw an explosive devi...,Unknown,Police,Explosives,2017-12-30
181665,2017.0,12.0,30.0,India,Chhattisgarh,South Asia,Toylanka,18.802725,81.497666,Facility/Infrastructure Attack,0.0,0.0,Road Construction Site,12/30/2017: Assailants set fire to seven vehic...,Communist Party of India - Maoist (CPI-Maoist),Business,Firearms,2017-12-30
181672,2017.0,12.0,31.0,India,Jammu and Kashmir,South Asia,Lethapora,33.966527,74.964225,Armed Assault,8.0,3.0,Camp,12/31/2017: Assailants armed with grenades and...,Jaish-e-Mohammad (JeM),Police,Explosives,2017-12-31
181684,2017.0,12.0,31.0,India,Assam,South Asia,Hungrum,25.180162,93.015788,Hostage Taking (Kidnapping),0.0,0.0,Personal Security Officer of Council Member Ih...,12/31/2017: Assailants abducted Prafulla Phuka...,Zeliangrong United Front,Government (General),Firearms,2017-12-31
181689,2017.0,12.0,31.0,India,Manipur,South Asia,Imphal,24.798346,93.940430,Bombing/Explosion,0.0,0.0,Office,12/31/2017: Assailants threw a grenade at a Fo...,Unknown,Government (General),Explosives,2017-12-31

In [673]:
filtered_data = filtered_data[filtered_data['Date'] >= '2014-05-26']

In [675]:
filtered_data

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type,Date
132468,2014.0,5.0,26.0,India,Andhra Pradesh,South Asia,Bandlapalli,14.714739,77.810281,Bombing/Explosion,0.0,0.0,Party Supporter,05/26/2014: An explosive device was discovered...,Unknown,Private Citizens & Property,Explosives,2014-05-26
132496,2014.0,5.0,26.0,India,West Bengal,South Asia,Sandeshkhali,22.356709,88.881991,Armed Assault,0.0,12.0,Party Workers,05/26/2014: Assailants opened fire on Bharatiy...,Unknown,Violent Political Party,Firearms,2014-05-26
132502,2014.0,5.0,26.0,India,West Bengal,South Asia,Sandeshkhali,22.363882,88.878679,Armed Assault,0.0,11.0,Members,05/26/2014: Assailants opened fire and threw e...,Unknown,Violent Political Party,Explosives,2014-05-26
132526,2014.0,5.0,27.0,India,Jammu and Kashmir,South Asia,Khour,32.601778,74.809414,Bombing/Explosion,0.0,0.0,Unknown,05/27/2014: An explosive device was discovered...,Unknown,Unknown,Explosives,2014-05-27
132555,2014.0,5.0,27.0,India,Odisha,South Asia,Bikrampur,22.338542,86.178146,Assassination,1.0,0.0,Journalist: Tarun Kumar Acharya,05/27/2014: Assailants stabbed and killed Taru...,Unknown,Journalists & Media,Melee,2014-05-27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181663,2017.0,12.0,30.0,India,Kerala,South Asia,Koothuparamba,11.831902,75.565432,Bombing/Explosion,0.0,0.0,Koothuparamba Police Station,12/30/2017: Assailants threw an explosive devi...,Unknown,Police,Explosives,2017-12-30
181665,2017.0,12.0,30.0,India,Chhattisgarh,South Asia,Toylanka,18.802725,81.497666,Facility/Infrastructure Attack,0.0,0.0,Road Construction Site,12/30/2017: Assailants set fire to seven vehic...,Communist Party of India - Maoist (CPI-Maoist),Business,Firearms,2017-12-30
181672,2017.0,12.0,31.0,India,Jammu and Kashmir,South Asia,Lethapora,33.966527,74.964225,Armed Assault,8.0,3.0,Camp,12/31/2017: Assailants armed with grenades and...,Jaish-e-Mohammad (JeM),Police,Explosives,2017-12-31
181684,2017.0,12.0,31.0,India,Assam,South Asia,Hungrum,25.180162,93.015788,Hostage Taking (Kidnapping),0.0,0.0,Personal Security Officer of Council Member Ih...,12/31/2017: Assailants abducted Prafulla Phuka...,Zeliangrong United Front,Government (General),Firearms,2017-12-31
181689,2017.0,12.0,31.0,India,Manipur,South Asia,Imphal,24.798346,93.940430,Bombing/Explosion,0.0,0.0,Office,12/31/2017: Assailants threw a grenade at a Fo...,Unknown,Government (General),Explosives,2017-12-31

In [677]:
total_attacks = filtered_data['AttackType'].count()
total_attacks

3336

In [683]:
filtered_data = filtered_data[filtered_data['Group'] != 'Unknown']
filtered_data

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type,Date
132559,2014.0,5.0,27.0,India,Meghalaya,South Asia,Daji Badimagre,25.396733,90.475623,Unknown,1.0,0.0,Suspected Informant: Sengran R. Marak,"05/27/2014: Assailants killed a civilian, Seng...",Garo National Liberation Army,Private Citizens & Property,Unknown,2014-05-27
132600,2014.0,5.0,28.0,India,Chhattisgarh,South Asia,Bijapur district,18.797297,80.813178,Armed Assault,1.0,0.0,Constable: Budhram Mudma,05/28/2014: Assailants stabbed Budhram Mudma i...,Maoists,Police,Melee,2014-05-28
132604,2014.0,5.0,28.0,India,Odisha,South Asia,Kambesu,19.280713,83.584336,Facility/Infrastructure Attack,0.0,0.0,Construction Camp,05/28/2014: Assailants set fire to equipment a...,Communist Party of India - Maoist (CPI-Maoist),Business,Incendiary,2014-05-28
132605,2014.0,5.0,28.0,India,Odisha,South Asia,Kusumaguda,19.042651,83.717257,Facility/Infrastructure Attack,0.0,0.0,Construction Camp,05/28/2014: Assailants set fire to equipment a...,Communist Party of India - Maoist (CPI-Maoist),Business,Incendiary,2014-05-28
132673,2014.0,5.0,29.0,India,Maharashtra,South Asia,Gadchiroli district,20.184871,79.994796,Assassination,1.0,0.0,Former Block Committee Member: Ghissu Mattami,05/29/2014: Assailants opened fire on a Nation...,Maoists,Government (General),Firearms,2014-05-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181606,2017.0,12.0,28.0,India,Bihar,South Asia,Sahajpur-Sahiyaar,24.744979,84.364248,Facility/Infrastructure Attack,0.0,0.0,Construction Site,12/28/2017: Assailants raided a road construct...,Maoists,Business,Incendiary,2017-12-28
181612,2017.0,12.0,28.0,India,Manipur,South Asia,Motbung,24.999834,93.903397,Hostage Taking (Kidnapping),0.0,0.0,Truck Driver: A. Akhikho,12/28/2017: Assailants stopped a truck and abd...,Manipur Naga People's Army (MNPA),Private Citizens & Property,Firearms,2017-12-28
181665,2017.0,12.0,30.0,India,Chhattisgarh,South Asia,Toylanka,18.802725,81.497666,Facility/Infrastructure Attack,0.0,0.0,Road Construction Site,12/30/2017: Assailants set fire to seven vehic...,Communist Party of India - Maoist (CPI-Maoist),Business,Firearms,2017-12-30
181672,2017.0,12.0,31.0,India,Jammu and Kashmir,South Asia,Lethapora,33.966527,74.964225,Armed Assault,8.0,3.0,Camp,12/31/2017: Assailants armed with grenades and...,Jaish-e-Mohammad (JeM),Police,Explosives,2017-12-31
181684,2017.0,12.0,31.0,India,Assam,South Asia,Hungrum,25.180162,93.015788,Hostage Taking (Kidnapping),0.0,0.0,Personal Security Officer of Council Member Ih...,12/31/2017: Assailants abducted Prafulla Phuka...,Zeliangrong United Front,Government (General),Firearms,2017-12-31

In [695]:
filtered_data['Group'].value_counts()

Group
Maoists                                                        854
Communist Party of India - Maoist (CPI-Maoist)                 327
Hizbul Mujahideen (HM)                                          78
Lashkar-e-Taiba (LeT)                                           69
Gorkha Janmukti Morcha (GJM)                                    67
                                                              ...
Tribal Revolutionary Army (TRA)                                  1
National Socialist Council of Nagaland-Unification (NSCN-U)      1
Revolutionary Communist Centre (RCC)                             1
Tiwa Liberation Army                                             1
Ansar Ghazwat-ul-Hind                                            1
Name: count, Length: 116, dtype: int64

In [697]:
active_grp = filtered_data['Group'].value_counts().idxmax()
active_grp

'Maoists'

In [699]:
print(total_attacks, active_grp, sep = '  ')

3336  Maoists

5.  Find Freq in Red Corridor States and J & K    --> Total casualty/Total num of year in Jharhkhand, Odisha, AP, Chattisgarh

In [39]:
df

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
0,1970.0,7.0,2.0,Dominican Republic,NaN,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,Assassination,1.0,0.0,Julio Guzman,NaN,MANO-D,Private Citizens & Property,Unknown
1,1970.0,0.0,0.0,Mexico,Federal,North America,Mexico city,19.371887,-99.086624,Hostage Taking (Kidnapping),0.0,0.0,"Nadine Chaval, daughter",NaN,23rd of September Communist League,Government (Diplomatic),Unknown
2,1970.0,1.0,0.0,Philippines,Tarlac,Southeast Asia,Unknown,15.478598,120.599741,Assassination,1.0,0.0,Employee,NaN,Unknown,Journalists & Media,Unknown
3,1970.0,1.0,0.0,Greece,Attica,Western Europe,Athens,37.997490,23.762728,Bombing/Explosion,NaN,NaN,U.S. Embassy,NaN,Unknown,Government (Diplomatic),Explosives
4,1970.0,1.0,0.0,Japan,Fukouka,East Asia,Fukouka,33.580412,130.396361,Facility/Infrastructure Attack,NaN,NaN,U.S. Consulate,NaN,Unknown,Government (Diplomatic),Incendiary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181686,2017.0,12.0,31.0,Somalia,Middle Shebelle,Sub-Saharan Africa,Ceelka Geelow,2.359673,45.385034,Armed Assault,1.0,2.0,Checkpoint,12/31/2017: Assailants opened fire on a Somali...,Al-Shabaab,Military,Firearms
181687,2017.0,12.0,31.0,Syria,Lattakia,Middle East & North Africa,Jableh,35.407278,35.942679,Bombing/Explosion,2.0,7.0,Hmeymim Air Base,12/31/2017: Assailants launched mortars at the...,Muslim extremists,Military,Explosives
181688,2017.0,12.0,31.0,Philippines,Maguindanao,Southeast Asia,Kubentog,6.900742,124.437908,Facility/Infrastructure Attack,0.0,0.0,Houses,12/31/2017: Assailants set fire to houses in K...,Bangsamoro Islamic Freedom Movement (BIFM),Private Citizens & Property,Incendiary
181689,2017.0,12.0,31.0,India,Manipur,South Asia,Imphal,24.798346,93.940430,Bombing/Explosion,0.0,0.0,Office,12/31/2017: Assailants threw a grenade at a Fo...,Unknown,Government (General),Explosives
181690,2017.0,12.0,31.0,Philippines,Maguindanao,Southeast Asia,Cotabato City,7.209594,124.241966,Bombing/Explosion,0.0,0.0,Unknown,12/31/2017: An explosive device was discovered...,Unknown,Unknown,Explosives

In [55]:
df['Casualty'] = df['Killed'] + df['Wounded']
df

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type,Casualty
0,1970.0,7.0,2.0,Dominican Republic,NaN,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,Assassination,1.0,0.0,Julio Guzman,NaN,MANO-D,Private Citizens & Property,Unknown,1.0
1,1970.0,0.0,0.0,Mexico,Federal,North America,Mexico city,19.371887,-99.086624,Hostage Taking (Kidnapping),0.0,0.0,"Nadine Chaval, daughter",NaN,23rd of September Communist League,Government (Diplomatic),Unknown,0.0
2,1970.0,1.0,0.0,Philippines,Tarlac,Southeast Asia,Unknown,15.478598,120.599741,Assassination,1.0,0.0,Employee,NaN,Unknown,Journalists & Media,Unknown,1.0
3,1970.0,1.0,0.0,Greece,Attica,Western Europe,Athens,37.997490,23.762728,Bombing/Explosion,NaN,NaN,U.S. Embassy,NaN,Unknown,Government (Diplomatic),Explosives,NaN
4,1970.0,1.0,0.0,Japan,Fukouka,East Asia,Fukouka,33.580412,130.396361,Facility/Infrastructure Attack,NaN,NaN,U.S. Consulate,NaN,Unknown,Government (Diplomatic),Incendiary,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181686,2017.0,12.0,31.0,Somalia,Middle Shebelle,Sub-Saharan Africa,Ceelka Geelow,2.359673,45.385034,Armed Assault,1.0,2.0,Checkpoint,12/31/2017: Assailants opened fire on a Somali...,Al-Shabaab,Military,Firearms,3.0
181687,2017.0,12.0,31.0,Syria,Lattakia,Middle East & North Africa,Jableh,35.407278,35.942679,Bombing/Explosion,2.0,7.0,Hmeymim Air Base,12/31/2017: Assailants launched mortars at the...,Muslim extremists,Military,Explosives,9.0
181688,2017.0,12.0,31.0,Philippines,Maguindanao,Southeast Asia,Kubentog,6.900742,124.437908,Facility/Infrastructure Attack,0.0,0.0,Houses,12/31/2017: Assailants set fire to houses in K...,Bangsamoro Islamic Freedom Movement (BIFM),Private Citizens & Property,Incendiary,0.0
181689,2017.0,12.0,31.0,India,Manipur,South Asia,Imphal,24.798346,93.940430,Bombing/Explosion,0.0,0.0,Office,12/31/2017: Assailants threw a grenade at a Fo...,Unknown,Government (General),Explosives,0.0
181690,2017.0,12.0,31.0,Philippines,Maguindanao,Southeast Asia,Cotabato City,7.209594,124.241966,Bombing/Explosion,0.0,0.0,Unknown,12/31/2017: An explosive device was discovered...,Unknown,Unknown,Explosives,0.0

In [45]:
df['Casualty'].isnull().sum()

18553

In [57]:
df = df.dropna(subset = ['Casualty'])

In [59]:
df

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type,Casualty
0,1970.0,7.0,2.0,Dominican Republic,NaN,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,Assassination,1.0,0.0,Julio Guzman,NaN,MANO-D,Private Citizens & Property,Unknown,1.0
1,1970.0,0.0,0.0,Mexico,Federal,North America,Mexico city,19.371887,-99.086624,Hostage Taking (Kidnapping),0.0,0.0,"Nadine Chaval, daughter",NaN,23rd of September Communist League,Government (Diplomatic),Unknown,0.0
2,1970.0,1.0,0.0,Philippines,Tarlac,Southeast Asia,Unknown,15.478598,120.599741,Assassination,1.0,0.0,Employee,NaN,Unknown,Journalists & Media,Unknown,1.0
5,1970.0,1.0,1.0,United States,Illinois,North America,Cairo,37.005105,-89.176269,Armed Assault,0.0,0.0,Cairo Police Headquarters,1/1/1970: Unknown African American assailants ...,Black Nationalists,Police,Firearms,0.0
6,1970.0,1.0,2.0,Uruguay,Montevideo,South America,Montevideo,-34.891151,-56.187214,Assassination,0.0,0.0,Juan Maria de Lucah/Chief of Directorate of in...,NaN,Tupamaros (Uruguay),Police,Firearms,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181686,2017.0,12.0,31.0,Somalia,Middle Shebelle,Sub-Saharan Africa,Ceelka Geelow,2.359673,45.385034,Armed Assault,1.0,2.0,Checkpoint,12/31/2017: Assailants opened fire on a Somali...,Al-Shabaab,Military,Firearms,3.0
181687,2017.0,12.0,31.0,Syria,Lattakia,Middle East & North Africa,Jableh,35.407278,35.942679,Bombing/Explosion,2.0,7.0,Hmeymim Air Base,12/31/2017: Assailants launched mortars at the...,Muslim extremists,Military,Explosives,9.0
181688,2017.0,12.0,31.0,Philippines,Maguindanao,Southeast Asia,Kubentog,6.900742,124.437908,Facility/Infrastructure Attack,0.0,0.0,Houses,12/31/2017: Assailants set fire to houses in K...,Bangsamoro Islamic Freedom Movement (BIFM),Private Citizens & Property,Incendiary,0.0
181689,2017.0,12.0,31.0,India,Manipur,South Asia,Imphal,24.798346,93.940430,Bombing/Explosion,0.0,0.0,Office,12/31/2017: Assailants threw a grenade at a Fo...,Unknown,Government (General),Explosives,0.0
181690,2017.0,12.0,31.0,Philippines,Maguindanao,Southeast Asia,Cotabato City,7.209594,124.241966,Bombing/Explosion,0.0,0.0,Unknown,12/31/2017: An explosive device was discovered...,Unknown,Unknown,Explosives,0.0

In [71]:
filtered_data = df.loc[(df['State'] == 'Jharkhand') | (df['State'] == 'Odisha') | (df['State'] == 'Andhra Pradesh') | (df['State'] == 'Chattisgarh')]
filtered_data

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type,Casualty
9053,1979.0,8.0,8.0,India,Andhra Pradesh,South Asia,Amapur,16.435329,77.831725,Unknown,1.0,1.0,town,NaN,Mizo National Front,Private Citizens & Property,Unknown,2.0
9148,1979.0,8.0,26.0,India,Jharkhand,South Asia,Jamshedpur,22.804567,86.202875,Bombing/Explosion,1.0,0.0,Hindu Religious Ceremony,NaN,Muslims,Religious Figures/Institutions,Explosives,1.0
9166,1979.0,8.0,29.0,India,Jharkhand,South Asia,Jamshedpur,22.804567,86.202875,Bombing/Explosion,3.0,14.0,several areas of Hhrijan quarter,NaN,Muslims,Private Citizens & Property,Explosives,17.0
27651,1986.0,3.0,26.0,India,Andhra Pradesh,South Asia,Anantapur,14.681888,77.600591,Assassination,0.0,0.0,"Cheif Minister Surjit Singh Barnala, Chief Min...",NaN,Sikh Extremists,Government (General),Unknown,0.0
33671,1988.0,3.0,3.0,India,Andhra Pradesh,South Asia,Chabala,15.035369,77.281460,Armed Assault,1.0,2.0,police patrol,NaN,Unknown,Police,Firearms,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181439,2017.0,12.0,20.0,India,Jharkhand,South Asia,Karaikela,22.707929,85.538869,Bombing/Explosion,0.0,0.0,Soldiers,12/20/2017: Five explosive devices were discov...,Communist Party of India - Maoist (CPI-Maoist),Military,Explosives,0.0
181471,2017.0,12.0,22.0,India,Andhra Pradesh,South Asia,Kumkumpudi,18.221027,82.703111,Facility/Infrastructure Attack,0.0,0.0,Earth Mover,12/22/2017: Assailants set fire to an earth mo...,Maoists,Business,Incendiary,0.0
181472,2017.0,12.0,22.0,India,Andhra Pradesh,South Asia,Gudem Kotha Veedhi,17.862932,82.197868,Hostage Taking (Kidnapping),0.0,0.0,Brother of Local Politician,12/22/2017: Assailants attempted to abduct the...,Maoists,Government (General),Unknown,0.0
181615,2017.0,12.0,28.0,India,Jharkhand,South Asia,Pandrasali,22.634353,85.811241,Hostage Taking (Barricade Incident),0.0,0.0,Construction Site,12/28/2017: Assailants raided a construction s...,Unknown,Business,Firearms,0.0
181661,2017.0,12.0,28.0,India,Andhra Pradesh,South Asia,Talacheru,17.001086,81.807490,Facility/Infrastructure Attack,1.0,0.0,Masjid,12/28/2017: Assailants attacked Noorani Masjid...,Unknown,Religious Figures/Institutions,Incendiary,1.0

In [75]:
total_casualty = filtered_data['Casualty'].sum()
total_casualty

3037.0

In [93]:
year_mask = filtered_data['Year'].unique()
year_mask

array([1979., 1986., 1988., 1989., 1990., 1991., 1992., 1994., 1995.,
       1996., 1997., 1998., 1999., 2000., 2001., 2002., 2003., 2004.,
       2005., 2006., 2007., 2008., 2009., 2010., 2011., 2012., 2013.,
       2014., 2015., 2016., 2017.])

In [87]:
year_mask.size

31

In [95]:
filtered_data['Year'].nunique()

31

In [89]:
Freq1 = total_casualty // year_mask.size
Freq1

97.0

In [97]:
filtered_data = df.loc[df['State'] == 'Jammu and Kashmir']
filtered_data

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type,Casualty
21744,1984.0,4.0,17.0,India,Jammu and Kashmir,South Asia,Bhela,33.315527,74.622476,Assassination,2.0,0.0,Gurbachan Singh Sandhar (Sikh lawyer) and wife,NaN,Sikh Extremists,Private Citizens & Property,Unknown,2.0
22108,1984.0,5.0,20.0,India,Jammu and Kashmir,South Asia,Jammu,32.726602,74.857026,Bombing/Explosion,1.0,0.0,bridge over a stream,NaN,Unknown,Transportation,Explosives,1.0
29677,1986.0,12.0,11.0,India,Jammu and Kashmir,South Asia,Madora,33.934929,75.154160,Bombing/Explosion,1.0,5.0,general post office complex,NaN,Unknown,Government (General),Unknown,6.0
33202,1988.0,1.0,21.0,India,Jammu and Kashmir,South Asia,Mand,32.888165,74.985168,Armed Assault,2.0,0.0,police unit,NaN,Unknown,Police,Firearms,2.0
33372,1988.0,2.0,7.0,India,Jammu and Kashmir,South Asia,Kherawali,32.523889,74.974444,Armed Assault,4.0,5.0,marriage reception,NaN,Sikh Extremists,Private Citizens & Property,Firearms,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181222,2017.0,12.0,11.0,India,Jammu and Kashmir,South Asia,Kralcheck Keller,33.732981,74.855559,Armed Assault,2.0,1.0,Van,12/11/2017: Assailants opened fire on a Jammu ...,Jaish-e-Mohammad (JeM),Business,Firearms,3.0
181396,2017.0,12.0,18.0,India,Jammu and Kashmir,South Asia,Baramulla district,34.191218,74.350010,Bombing/Explosion,0.0,0.0,Police Station,12/18/2017: Assailants threw a grenade at a po...,Unknown,Police,Explosives,0.0
181414,2017.0,12.0,19.0,India,Jammu and Kashmir,South Asia,Pulwama district,33.873538,74.899019,Bombing/Explosion,0.0,0.0,Police Line,12/19/2017: Assailants fired a rifle grenade a...,Unknown,Police,Explosives,0.0
181476,2017.0,12.0,22.0,India,Jammu and Kashmir,South Asia,Srinagar,34.083740,74.789902,Armed Assault,0.0,0.0,Post,12/22/2017: Assailants threw two petrol bombs ...,Unknown,Police,Incendiary,0.0
181672,2017.0,12.0,31.0,India,Jammu and Kashmir,South Asia,Lethapora,33.966527,74.964225,Armed Assault,8.0,3.0,Camp,12/31/2017: Assailants armed with grenades and...,Jaish-e-Mohammad (JeM),Police,Explosives,11.0

In [103]:
total_casualty = filtered_data['Casualty'].sum()
total_casualty

12268.0

In [105]:
year_mask = filtered_data['Year'].nunique()
year_mask

31

In [109]:
filtered_data['Year'].unique()

array([1984., 1986., 1988., 1989., 1990., 1991., 1992., 1994., 1995.,
       1996., 1997., 1998., 1999., 2000., 2001., 2002., 2003., 2004.,
       2005., 2006., 2007., 2008., 2009., 2010., 2011., 2012., 2013.,
       2014., 2015., 2016., 2017.])

In [111]:
Freq2 = total_casualty // year_mask
Freq2

395.0

In [113]:
print(Freq1, Freq2, sep = '  ')

97.0  395.0